# Generated by Django 6.0.3 on 2026-03-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_github_url_alter_project_demo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='repo_url',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Application'), ('app', 'Mobile Application'), ('tool', 'Security Tool'), ('script', 'Automation / Script'), ('ctf', 'CTF / Writeups'), ('other', 'Other')], default='web', max_length=20),
        ),
    ]
