# Generated by Django 6.0.1 on 2026-03-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credential_url', models.URLField(blank=True, help_text='URL du certificat ou de la vérification')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress')], default='completed', max_length=20)),
                ('date', models.DateField(help_text="Date d'obtention ou de début")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
