# Generated by Django 6.0.3 on 2026-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('experience_type', models.CharField(choices=[('education', 'Education'), ('lab', 'Personal Lab'), ('ctf', 'CTF / Competition'), ('work', 'Professional Experience'), ('project', 'Project'), ('certification', 'Certification')], default='education', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordre sur la timeline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
