# Generated by Django 6.0.3 on 2026-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('pentesting', 'Penetration Testing'), ('networking', 'Networking'), ('programming', 'Programming'), ('web', 'Web'), ('security', 'Security'), ('other', 'Other')], max_length=30)),
                ('level', models.PositiveIntegerField(default=70, help_text='Niveau de 0 à 100 pour l’animation des barres')),
                ('icon', models.CharField(blank=True, help_text='Nom d’icône (par ex. Heroicons / Lucide côté frontend)', max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', '-level'],
            },
        ),
    ]
